const ERROR_DATA_CODE = 400;
const INCORRECT_EMAIL_OR_PASSWORD = 401;
const REMOVING_ANOTHER_USER_IS_CARD = 403;
const NOT_FOUND_CODE = 404;
const USED_EMAIL = 409;
const SERVER_ERROR_CODE = 500;
const OK = 200;
const CREATED = 201;

module.exports = {
  ERROR_DATA_CODE,
  INCORRECT_EMAIL_OR_PASSWORD,
  REMOVING_ANOTHER_USER_IS_CARD,
  USED_EMAIL,
  NOT_FOUND_CODE,
  SERVER_ERROR_CODE,
  OK,
  CREATED,
};
