const ERROR_DATA_CODE = 400;
const NOT_FOUND_CODE = 404;
const SERVER_ERROR_CODE = 500;
const REQUEST_OK = 200;
const CREATED_RESOURCE = 201;

module.exports = {
  ERROR_DATA_CODE,
  NOT_FOUND_CODE,
  SERVER_ERROR_CODE,
  REQUEST_OK,
  CREATED_RESOURCE,
};
